crimeRating = {
  Assault: 90,
  Robbery: 85,
  Intimidation: 60,
  Weapons: 60,
  Theft: 50,
  Stolen: 50,
  Burglary: 50,
  Traffic: 40,
  Offences: 20,
  Warrant: 15,
  Missing: 12,
  Drug: 10,
  Disorderly: 10,
  Suspicious: 10,
  'Malicious Mischief': 5,
  Vandalism: 5,
  Miscellaneous: 1,
  Lost: 1,
  Other: 1,
  Fraud: 0,
  Forgery: 0,
  Embezzlement: 0,
}

module.exports = crimeRating;
